User:
    type: object
    properties:
        id:
            type: integer
        name:
            type: string
Media:
    type: Object
    properties:
        disk:
            disk:
                type: string
        directory:
            directory:
                type: string
        filename:
            filename:
                type: string
        mime_type:
            mime_type:
                type: string
        aggregate_type:
            aggregate_type:
                type: string
